ALTER TABLE "StaticPageContent"
  ADD COLUMN IF NOT EXISTS "titleFontSize" INTEGER NOT NULL DEFAULT 56,
  ADD COLUMN IF NOT EXISTS "titleAlign" VARCHAR(16) NOT NULL DEFAULT 'left',
  ADD COLUMN IF NOT EXISTS "subtitleFontSize" INTEGER NOT NULL DEFAULT 18,
  ADD COLUMN IF NOT EXISTS "subtitleAlign" VARCHAR(16) NOT NULL DEFAULT 'left',
  ADD COLUMN IF NOT EXISTS "heroImageUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "bodyHtml" TEXT,
  ADD COLUMN IF NOT EXISTS "bodyFontSize" INTEGER NOT NULL DEFAULT 16,
  ADD COLUMN IF NOT EXISTS "bodyAlign" VARCHAR(16) NOT NULL DEFAULT 'left';
